services:
  postgres:
    image: postgres:15-alpine
    container_name: workflow-builder-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - workflow-builder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../workflow-builder-api
      dockerfile: Dockerfile
    container_name: workflow-builder-api
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 3001
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASS: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}
    ports:
      - "${BACKEND_PORT}:3001"
    volumes:
      - ../workflow-builder-api:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - workflow-builder-network
    restart: unless-stopped

  frontend:
    build:
      context: ../workflow-builder-site
      dockerfile: Dockerfile
    container_name: workflow-builder-frontend
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ../workflow-builder-site:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - workflow-builder-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  workflow-builder-network:
    driver: bridge
